apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest

# kubectl apply -f 01_pod.yaml
# kubectl get pods
# kubectl exec -it nginx -- sh
# kubectl logs nginx
# kubectl delete pod nginx
# kubectl get pods nginx -o yaml