apiVersion: v1
kind: Pod
metadata:
  name: flask-kubernetes-app
spec:
  containers:
  - name: flask-kubernetes-app
    image: flask-kubernetes
    env:
    - name: FLASK_DEBUG
      value: "1"
    - name: FLASK_APP
      value: "app.py"
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi" # linux kernel kills the process if it uses more than 128Mi of memory
        cpu: "500m" # 1000m = 1 core # cpu full load
    readinessProbe: # says kubernetes that the pod is ready to receive traffic
      httpGet:
        path: /
        port: 5000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: # says kubernetes that the pod is alive
      tcpSocket:
        port: 5000
      initialDelaySeconds: 15
      periodSeconds: 20
    ports:
      - containerPort: 5000
        protocol: TCP