apiVersion: apps/v1
kind: DaemonSet # Daemonset is a type of Deployment that runs 1 pod that is present on all nodes. Doesnt have replicas (monitoring nodes)
metadata:
  name: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        # env:
        # - name: PORT
        #   value: "80"
        # - name: HOST
        #   value: "nginx"
        # - name: HOST_IP
        #   valueFrom:
        #     fieldRef:
        #       fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 80

# kubectl apply -f 03_deployment.yaml
# kubectl delete -f .\04_daemonset.yaml