apiVersion: v1
kind: Service
metadata:
  name: flask-kubernetes-service
spec:
  selector:
    app: flask-kubernetes-app
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kubernetes-app
spec:
  selector:
    matchLabels:
      app: flask-kubernetes-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-kubernetes-app
    spec:
      containers:
      - name: flask-kubernetes-app
        image: flask-kubernetes
        imagePullPolicy: Never
        resources:
          requests:
            memory: 64Mi
            cpu: "0.25"
          limits:
            memory: 128Mi
            cpu: "0.5"
        ports:
        - containerPort: 5000