apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-kubernetes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-kubernetes-app
  template:
    metadata:
      labels:
        app: flask-kubernetes-app
    spec:
      containers:
      - name: flask-kubernetes-app
        image: flask-kubernetes
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 64Mi
            cpu: "0.25"
          limits:
            memory: 128Mi
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-kubernetes-service
spec:
  type: LoadBalancer
  selector:
    app: flask-kubernetes-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-kubernetes-service
# spec:
#   type: NodePort
#   selector:
#     app: flask-kubernetes-app
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 30001