apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME # variable on app
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD # variable on app
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: DB_URL # variable on app
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url # mongo-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service # webapp-service.yaml
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 3000 # Port of service, can be eg: 8080 
    targetPort: 3000 # deployment pod containerPort
    nodePort: 30100

